//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerFest
{
    using System;
    using System.Collections.Generic;
    
    public partial class arquivos
    {
        public string tipo { get; set; }
        public string caminho { get; set; }
        public int id_arquivo { get; set; }
        public Nullable<int> id_servico { get; set; }
    
        public virtual Servico Servico { get; set; }
    }
}
