//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerFest
{
    using System;
    using System.Collections.Generic;
    
    public partial class avaliacao
    {
        public string tp_avaliacao { get; set; }
        public string titulo_avaliacao { get; set; }
        public string opiniao { get; set; }
        public string recomendado { get; set; }
        public Nullable<System.DateTime> data_avaliacao { get; set; }
        public int id_avaliacao { get; set; }
        public Nullable<int> id_servico { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual Servico Servico { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
