//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerFest
{
    using System;
    using System.Collections.Generic;
    
    public partial class contato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contato()
        {
            this.Empresa = new HashSet<Empresa>();
        }
    
        public int id_contato { get; set; }
        public string cidade { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string telefone1 { get; set; }
        public string telefone2 { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresa> Empresa { get; set; }
    }
}
