//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerFest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class powerFestFinalEntities : DbContext
    {
        public powerFestFinalEntities()
            : base("name=powerFestFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arquivos> arquivos { get; set; }
        public virtual DbSet<avaliacao> avaliacao { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<contato> contato { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Servico> Servico { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
