//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerFest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int id_empresa { get; set; }
        public string cnpj { get; set; }
        public string logradouro { get; set; }
        public string pais { get; set; }
        public string razao_social { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string email { get; set; }
        public Nullable<int> id_contato { get; set; }
        public Nullable<int> id_servico { get; set; }
        public string telefone2 { get; set; }
        public string telefone1 { get; set; }
    
        public virtual contato contato { get; set; }
        public virtual Servico Servico { get; set; }
    }
}
