//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerFest
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.avaliacao = new HashSet<avaliacao>();
            this.contato = new HashSet<contato>();
        }
    
        public Nullable<System.DateTime> dt_cadastro { get; set; }
        [DisplayName("Login")]
        public string login { get; set; }
        [DisplayName("Senha")]
        public string senha { get; set; }
        public string email { get; set; }
        public int id_usuario { get; set; }
        public int id_perfil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<avaliacao> avaliacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contato> contato { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
